name: Test trigger

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          echo "MANIFEST=main" >> $GITHUB_ENV
      - name: Test
        run: |
          echo ${MANIFEST}
          echo ${{ env.MANIFEST }}
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: AAndrisa/adi-kuiper-gen
      #     event-type: my-event
      #     client-payload: '{"ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'