name: Test trigger

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          echo "MANIFEST=main" >> $GITHUB_ENV
      - name: Test
        run: |
          #!/bin/bash
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ secrets.PRIVATE_ORG_NAME }}/${{ secrets.PRIVATE_REPO_NAME }}/dispatches \
            -d '{
              "event_type": "external_trigger",
              "client_payload": {
                "source": "manual_trigger",
                "environment": "production",
                "message": "Triggered via curl"
              }
            }'
